// Generated by scripts/generate_enums.py. Do not edit by hand.

export const SessionStatus = Object.freeze({
  "WAITING_FOR_UPLOAD": "waiting_for_upload",
  "UPLOADING": "uploading",
  "ASSEMBLING": "assembling",
  "UPLOADED": "uploaded",
  "QUEUED": "queued",
  "PROCESSING": "processing",
  "CROPPED": "cropped",
  "COMPLETED": "completed",
  "FAILED": "failed",
  "CANCELLED": "cancelled"
});

export const PipelineStep = Object.freeze({
  "WHISPERX": "whisperx",
  "AUDIO_EXTRACTION": "audio_extraction",
  "TRANSCRIPTION": "transcription",
  "TRANSCRIPT_NORMALIZATION": "transcript_normalization",
  "LLM_PREPROCESS": "llm_preprocess",
  "AUDIO_PROFESSIONALISM": "audio_professionalism",
  "COMMUNICATION_SCORING": "communication_scoring",
  "CONTENT_SCORING": "content_scoring",
  "ASSESSMENT_PERSISTENCE": "assessment_persistence",
  "PERSON_DETECTION": "person_detection",
  "BELL_DETECTION": "bell_detection"
});

export const StepStatus = Object.freeze({
  "RUNNING": "running",
  "COMPLETED": "completed",
  "FAILED": "failed",
  "SKIPPED": "skipped"
});

export const UploadStatus = Object.freeze({
  "INITIATED": "initiated",
  "UPLOADING": "uploading",
  "ASSEMBLING": "assembling",
  "COMMITTED": "committed",
  "FAILED": "failed",
  "ABORTED": "aborted",
  "EXPIRED": "expired"
});

export const ClipExportStatus = Object.freeze({
  "QUEUED": "queued",
  "RUNNING": "running",
  "COMPLETED": "completed",
  "FAILED": "failed"
});

export const JobStatus = Object.freeze({
  "WAITING_FOR_UPLOAD": "waiting_for_upload",
  "QUEUED": "queued",
  "RUNNING": "running",
  "SUCCEEDED": "succeeded",
  "FAILED": "failed",
  "CANCELLED": "cancelled"
});

export const TaskType = Object.freeze({
  "PROCESS_SESSION": "process_session",
  "AUTO_CROP": "auto_crop",
  "EXPORT_CLIPS": "export_clips"
});

export const Workflow = Object.freeze({
  "STANDARD": "standard",
  "LONG": "long"
});

export const SegmentationMethod = Object.freeze({
  "BELLS": "bells",
  "PERSON": "person"
});

export const ClipKind = Object.freeze({
  "SESSION": "session",
  "INTERMISSION": "intermission"
});

export const UploadFileKind = Object.freeze({
  "VIDEO": "video",
  "CASE_STUDY": "caseStudy"
});

export const OutputKey = Object.freeze({
  "AUDIO": "audio",
  "WHISPERX_JSON": "whisperxJson",
  "TRANSCRIPT": "transcript",
  "SUBTITLE": "subtitle",
  "SUBTITLE_TRACK": "subtitleTrack",
  "AUDIO_PROFESSIONALISM": "audioProfessionalism",
  "COMMUNICATION_SCORES": "communicationScores",
  "VIDEO_CLIPS": "videoClips",
  "SCORES": "scores"
});

export const MarkingMode = Object.freeze({
  "SINGLE": "single",
  "PANEL": "panel"
});

export const TieBreak = Object.freeze({
  "LENIENT": "lenient",
  "STRICT": "strict",
  "FIRST_MARKER": "first_marker"
});

export const IN_FLIGHT_STATUSES = new Set(["assembling", "processing", "queued"]);
