"""Generate the browser's wire vocabulary; --check detects stale exports."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import llm_bootstrap  # noqa: F401
from app.domain.enums import (
    ClipExportScope,
    ClipExportStatus,
    ClipKind,
    OutputKey,
    PipelineStep,
    ScoreDisplay,
    SegmentationMethod,
    StepStatus,
    TaskType,
    UploadFileKind,
    UploadStatus,
    Workflow,
)
from app.domain.jobs import JobStatus
from app.domain.sessions import IN_FLIGHT_STATUSES, SessionStatus
from app.domain.users import UserRole, UserStatus
from app.llm.panel import MarkingMode, TieBreak


def render() -> str:
    definitions = [
        "// Generated by scripts/generate_enums.py. Do not edit by hand.\n",
    ]
    for enum in (
        SessionStatus, PipelineStep, StepStatus, UploadStatus, ClipExportStatus, ClipExportScope,
        JobStatus, TaskType, Workflow, SegmentationMethod, ClipKind, UploadFileKind, OutputKey,
        MarkingMode, TieBreak, UserRole, UserStatus, ScoreDisplay,
    ):
        values = {item.name: item.value for item in enum}
        definitions.append(
            f"export const {enum.__name__} = Object.freeze({json.dumps(values, indent=2)});\n"
        )
    definitions.append(
        f"export const IN_FLIGHT_STATUSES = new Set({json.dumps(sorted(IN_FLIGHT_STATUSES))});\n"
    )
    return "\n".join(definitions)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / "src/lib/enums.js"
    content = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale enum exports: run python scripts/generate_enums.py")
    else:
        path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
